service: le-aws-cloudwatch

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-southeast-2
  environment:
    region: ${opt:le-region, env:LOGENTRIES_REGION}
    token: ${opt:le-token, env:LOGENTRIES_TOKEN}

package:
  exclude:
    - .gitignore
    - .idea
    - le-aws-cloudwatch/doc/**
    - le-aws-cloudwatch/LICENSE
    - le-aws-cloudwatch/README.md

functions:
  stream-handler:
    handler: le-aws-cloudwatch/le_cloudwatch.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - cloudwatchLog: ${opt:cw-log, env:CLOUDWATCH_LOG}
